### ISSUE TITLE
Align S3 handling with the latest commons method

### ISSUE THREAD

**Issue by yuanzhou** [x-atlas-consortia/uuid-api#162]
When I tried to update the commons from 2.1.15 to 2.1.18 in uuid-api, the API failed to start:

```
[2024-10-17 17:48:35] ERROR in uuid_worker: Error initializing theS3Worker - '__init__() missing 2 required positional arguments: 'LARGE_RESPONSE_THRESHOLD' and 'SERVICE_S3_OBJ_PREFIX''.
Traceback (most recent call last):
  File "/usr/src/app/src/./uuid_worker.py", line 339, in __init__
    self.theS3Worker = S3Worker(self.S3_settings_dict['aws_access_key_id']
TypeError: __init__() missing 2 required positional arguments: 'LARGE_RESPONSE_THRESHOLD' and 'SERVICE_S3_OBJ_PREFIX'
[2024-10-17 17:48:35] CRITICAL in app: Unable to instantiate a UUIDWorker during startup.
Error instantiating a UUIDWorker during startup.
Unexpected error: __init__() missing 2 required positional arguments: 'LARGE_RESPONSE_THRESHOLD' and 'SERVICE_S3_OBJ_PREFIX'
[2024-10-17 17:48:35] ERROR in app: Unexpected error: __init__() missing 2 required positional arguments: 'LARGE_RESPONSE_THRESHOLD' and 'SERVICE_S3_OBJ_PREFIX'
Traceback (most recent call last):
  File "/usr/src/app/src/./uuid_worker.py", line 339, in __init__
    self.theS3Worker = S3Worker(self.S3_settings_dict['aws_access_key_id']
TypeError: __init__() missing 2 required positional arguments: 'LARGE_RESPONSE_THRESHOLD' and 'SERVICE_S3_OBJ_PREFIX'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/src/./app.py", line 46, in <module>
    worker = UUIDWorker(app_config=app.config)
  File "/usr/src/app/src/./uuid_worker.py", line 346, in __init__
    raise Exception(f"Unexpected error: {str(e)}")
Exception: Unexpected error: __init__() missing 2 required positional arguments: 'LARGE_RESPONSE_THRESHOLD' and 'SERVICE_S3_OBJ_PREFIX'
Traceback (most recent call last):
  File "/usr/src/app/src/./uuid_worker.py", line 339, in __init__
    self.theS3Worker = S3Worker(self.S3_settings_dict['aws_access_key_id']
TypeError: __init__() missing 2 required positional arguments: 'LARGE_RESPONSE_THRESHOLD' and 'SERVICE_S3_OBJ_PREFIX'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/src/./app.py", line 46, in <module>
    worker = UUIDWorker(app_config=app.config)
  File "/usr/src/app/src/./uuid_worker.py", line 346, in __init__
    raise Exception(f"Unexpected error: {str(e)}")
Exception: Unexpected error: __init__() missing 2 required positional arguments: 'LARGE_RESPONSE_THRESHOLD' and 'SERVICE_S3_OBJ_PREFIX'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/src/./wsgi.py", line 1, in <module>
    from app import app as application
  File "/usr/src/app/src/./app.py", line 53, in <module>
    print("Check the log file for further information: " + LOG_FILE_NAME)
NameError: name 'LOG_FILE_NAME' is not defined
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
```

**Comment by kburke** [comment]
https://github.com/x-atlas-consortia/uuid-api/pull/165
